#cloud-config

package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - unzip
  - python3
  - yum-utils

write_files:
  - path: /opt/app-runtime/deploy.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e

      APP_NAME="${app_name}"
      DEPLOY_MODE="${deploy_mode}"

      CONTAINER_PORT="${container_port}"
      OCIR_REGISTRY="${ocir_registry}"
      OCIR_USERNAME_SECRET_ID="${ocir_username_secret_id}"
      OCIR_TOKEN_SECRET_ID="${ocir_token_secret_id}"
      OCIR_NAMESPACE="${ocir_namespace}"

      FULL_IMAGE="$OCIR_REGISTRY/$OCIR_NAMESPACE/$APP_NAME:${image_tag}"

      usermod -aG docker opc || true

      if ! command -v oci >/dev/null 2>&1; then
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o /tmp/install_oci.sh
        bash /tmp/install_oci.sh --accept-all-defaults
        export PATH="$PATH:/root/bin"
      fi

      OCIR_USERNAME=$(oci secrets secret-bundle get \
        --auth instance_principal \
        --secret-id "$OCIR_USERNAME_SECRET_ID" \
        --query 'data."secret-bundle-content".content' \
        --raw-output 2>/dev/null | base64 -d)

      OCIR_TOKEN=$(oci secrets secret-bundle get \
        --auth instance_principal \
        --secret-id "$OCIR_TOKEN_SECRET_ID" \
        --query 'data."secret-bundle-content".content' \
        --raw-output 2>/dev/null | base64 -d)

      echo "$OCIR_TOKEN" | docker login "$OCIR_REGISTRY" \
        -u "$OCIR_USERNAME" \
        --password-stdin

      docker pull "$FULL_IMAGE"

      if [ "$DEPLOY_MODE" = "docker-compose" ]; then
 
          docker compose down || true
          docker compose up -d

      else

          docker rm -f "$APP_NAME" || true

          docker run -d \
            --name "$APP_NAME" \
            --restart unless-stopped \
            -p 8080:"$CONTAINER_PORT" \
            "$FULL_IMAGE"
      fi
      echo "App deployed successfully: $FULL_IMAGE" > /opt/app-runtime/init.log

runcmd:
  - dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker
  - mkdir -p /opt/app-runtime
  - /opt/app-runtime/deploy.sh
 